[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  functions = "netlify/functions"

[functions."snapshot"]
schedule = "*/15 6-10 * * *"

[functions."snapshot-offpeak"]
schedule = "30 * * * *"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
